### ISSUE TITLE
eine Konstante 1 zum Dataframe hinzufügen

### ISSUE THREAD

**Issue by Array4064** [Simon95H/eda2#38]
damit im Anschluss das add Constand aus den Regressionsmodellen entfernt werden kann. Da diese Sehr häufig nicht signifikant sind.

**Comment by Simon95H** [comment]
sm.add_constant funktioniert nur bei DataFrames etc, die eine Länge >1 haben. Daher ist jetzt statt der Funktion einfach ein ".assign(const=1) hinter dem Dataframe der jeweiligen Datanauswahl der Predictions.

Wenn man beim Trainingsmodell die const auslässt, dann wird sie auch bei den Tets und Validierungen nicht berücksichtigt. Daher ist über den Parameter const jetzt als boolean zu entscheiden, ob mit oder oder Konstante gerechnet wird.
